# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    enable_automatic_code_signing
    increment_build_number
    build_app(
      workspace: "Shortlist.xcworkspace",
      scheme: "Shortlist",
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates",
    )
    upload_to_testflight
  end

  # desc "Code Signing"
  # lane :codeSign do
  #   cert(
  #       username: "markhmwong@gmail.com"
  #       )
  #   sigh(
  #       force: true, username: "markhmwong@gmail.com"
  #       )
  # end

  lane :certs do
    update_project_team(
      path: "Shortlist.xcodeproj",
      teamid: "GEKZN86RYS"
    )
    match(type: "appstore", app_identifier: ["com.whizbang.shortlist", "com.whizbang.shortlist.watchkitapp", "com.whizbang.shortlist.watchkitapp.watchkitextension"])
    match(type: "development", app_identifier: ["com.whizbang.shortlist", "com.whizbang.shortlist.watchkitapp", "com.whizbang.shortlist.watchkitapp.watchkitextension"])
    match(type: "adhoc", app_identifier: ["com.whizbang.shortlist", "com.whizbang.shortlist.watchkitapp", "com.whizbang.shortlist.watchkitapp.watchkitextension"])
  end


  desc "App Store Release"
  lane :release do
    # enable_automatic_code_signing
    get_provisioning_profile(app_identifier: "com.whizbang.shortlist")
    get_provisioning_profile(app_identifier: "com.whizbang.shortlist.watchkitapp")
    get_provisioning_profile(app_identifier: "com.whizbang.shortlist.watchkitapp.watchkitextension")

    increment_build_number
    increment_version_number(
      #bump_type: "minor"
      version_number: "1.2.4"
    )

    build_app(
      workspace: "Shortlist.xcworkspace",
      scheme: "Shortlist",
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates",
    ) 
    

    upload_to_app_store
  end
end
